// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/leistungen": {
    params: {};
  };
  "/projekte": {
    params: {};
  };
  "/ueber-mich": {
    params: {};
  };
  "/kontakt": {
    params: {};
  };
  "/datenschutz": {
    params: {};
  };
  "/cookie-richtlinie": {
    params: {};
  };
  "/impressum": {
    params: {};
  };
  "/agb": {
    params: {};
  };
  "/404": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/leistungen" | "/projekte" | "/ueber-mich" | "/kontakt" | "/datenschutz" | "/cookie-richtlinie" | "/impressum" | "/agb" | "/404" | "/*";
  };
  "./layout/Layout.jsx": {
    id: "layout/Layout";
    page: "/" | "/leistungen" | "/projekte" | "/ueber-mich" | "/kontakt" | "/datenschutz" | "/cookie-richtlinie" | "/impressum" | "/agb" | "/404" | "/*";
  };
  "./pages/HomePage.jsx": {
    id: "pages/HomePage";
    page: "/";
  };
  "./pages/ServicesPage.jsx": {
    id: "pages/ServicesPage";
    page: "/leistungen";
  };
  "./pages/ProjectsPage.jsx": {
    id: "pages/ProjectsPage";
    page: "/projekte";
  };
  "./pages/AboutPage.jsx": {
    id: "pages/AboutPage";
    page: "/ueber-mich";
  };
  "./pages/ContactPage.jsx": {
    id: "pages/ContactPage";
    page: "/kontakt";
  };
  "./pages/PrivacyPolicyPage.jsx": {
    id: "pages/PrivacyPolicyPage";
    page: "/datenschutz";
  };
  "./pages/CookiesPolicyPage.jsx": {
    id: "pages/CookiesPolicyPage";
    page: "/cookie-richtlinie";
  };
  "./pages/ImprintPage.jsx": {
    id: "pages/ImprintPage";
    page: "/impressum";
  };
  "./pages/TermsAndConditionsPage.jsx": {
    id: "pages/TermsAndConditionsPage";
    page: "/agb";
  };
  "./pages/NotFoundPage.jsx": {
    id: "pages/NotFoundPage";
    page: "/404";
  };
  "./pages/CatchAllRedirect.jsx": {
    id: "pages/CatchAllRedirect";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "layout/Layout": typeof import("./src/./layout/Layout.jsx");
  "pages/HomePage": typeof import("./src/./pages/HomePage.jsx");
  "pages/ServicesPage": typeof import("./src/./pages/ServicesPage.jsx");
  "pages/ProjectsPage": typeof import("./src/./pages/ProjectsPage.jsx");
  "pages/AboutPage": typeof import("./src/./pages/AboutPage.jsx");
  "pages/ContactPage": typeof import("./src/./pages/ContactPage.jsx");
  "pages/PrivacyPolicyPage": typeof import("./src/./pages/PrivacyPolicyPage.jsx");
  "pages/CookiesPolicyPage": typeof import("./src/./pages/CookiesPolicyPage.jsx");
  "pages/ImprintPage": typeof import("./src/./pages/ImprintPage.jsx");
  "pages/TermsAndConditionsPage": typeof import("./src/./pages/TermsAndConditionsPage.jsx");
  "pages/NotFoundPage": typeof import("./src/./pages/NotFoundPage.jsx");
  "pages/CatchAllRedirect": typeof import("./src/./pages/CatchAllRedirect.jsx");
};